import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from 'components/sections/Navbar'
import Wrapper from 'components/layout/Wrapper'
import Hero from 'components/sections/Hero'
import Testimonials from 'components/sections/Testimonials'
import About from 'components/sections/About'
import News from 'components/sections/News.jsx'
import Career from 'components/sections/Career'
import Footer from 'components/sections/Footer'
import Anchor from 'components/ui/Anchor'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <Testimonials/>
      <About/>
      <News/>
      <Career/>
      {/* <Anchor/> */}
      <Footer/>

    </>
  )
}
